version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
          JOBS: 1
    steps:
      - checkout
      - run:
          name: Install node global dependencies
          command: sudo npm install -g ember-cli
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Ember Tests
          command: ember try:each
